server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # הגדרה ספציפית ל-PDF שתמנע את החסימה
    location ~* \.pdf$ {
        root /usr/share/nginx/html;
        add_header Content-Type application/pdf;
        add_header Content-Disposition "attachment; filename=Yasmina_Halabi_CV.pdf";
        
        #Headers למניעת חסימת דפדפן (CORS)
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        add_header Cache-Control "no-cache";
    }
}