server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # הגדרה לקבצים סטטיים - מוודא שהם לא יורדו ריקים
    location ~* \.(pdf|jpg|jpeg|png|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        add_header Cache-Control "public, no-transform";
        add_header Content-Type application/pdf;
    }
}